version: "3.2"

services:
  api:
    container_name: node-express-api
    restart: always
    build: .
    command: yarn start
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/api
    links:
      - db

  db:
    container_name: node-express-mongo-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db

volumes:
  mongodb_data_volume:
    external: true
