version: "3.2"

services:
  api:
    container_name: julianosilva94-ekki-api
    restart: always
    build: .
    command: yarn start
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/api
    links:
      - db

  db:
    container_name: julianosilva94-ekki-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db

volumes:
  mongodb_data_volume:
    external: true